Numpy
  - Utilizada em cálculos matemáticos;
  - O pandas usa o numpy "por baixo dos panos";
  - O numpy trabalha com conceito de vetor;


Função Array:

In [1]:
import numpy as np

In [7]:
d = [1, 2, 3, 4, 5, 6]
arr = np.array(d)
arr

array([1, 2, 3, 4, 5, 6])

In [8]:
arr.dtype

dtype('int64')

In [9]:
np.shape(arr)

(6,)

In [10]:
np.size(arr)

6

In [12]:
d2 = [ [1, 3, 5, 7 ], [3, 55, 6, 90] ]
arr1 = np.array(d2)
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [13]:
np.shape(arr1)

(2, 4)

In [14]:
arr1[1, 2]

6

In [19]:
arr1[0, :]

array([1, 3, 5, 7])

In [20]:
arr1[1, 1:3]

array([55,  6])

In [23]:
empty_array = np.empty(6, dtype='int32')
empty_array

array([1410433056,      23733,          0,          0,         64,
                0], dtype=int32)

In [26]:
np.empty([2,2], dtype='int32')

array([[          0, -1073741824],
       [  -68190209,       31584]], dtype=int32)

In [27]:
np.random.randint(0, 57, size=(3,3))

array([[18, 14, 48],
       [ 7, 49, 10],
       [50, 48, 10]])

In [28]:
np.random.rand(3,3)

array([[0.80335513, 0.87532415, 0.07224779],
       [0.20870359, 0.6801624 , 0.37471039],
       [0.3727143 , 0.06237541, 0.47299548]])

Matemática com Arrays:

In [29]:
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [30]:
arr3 = arr1 * 2
arr3

array([[  2,   6,  10,  14],
       [  6, 110,  12, 180]])

In [32]:
arr33 = arr1 / 2
arr3

array([[ 0.5,  1.5,  2.5,  3.5],
       [ 1.5, 27.5,  3. , 45. ]])

In [33]:
arr333 = arr1 + 2
arr333

array([[ 3,  5,  7,  9],
       [ 5, 57,  8, 92]])

In [34]:
subArr = np.subtract(arr3, arr1)
subArr

array([[ -0.5,  -1.5,  -2.5,  -3.5],
       [ -1.5, -27.5,  -3. , -45. ]])

In [35]:
arr1.mean()

21.25

In [36]:
arr1.std()

30.90610781059304

In [38]:
arr1.cumsum(axis=1) #soma acumulada

array([[  1,   4,   9,  16],
       [  3,  58,  64, 154]])

Transformações de Arrays:

In [39]:
arr4 = np.arange(8)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
arr5 = arr4.reshape(4, 2) #4 linhas e 2 colunas
arr5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [42]:
arr6 = arr5.reshape(2, 4)
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
arr7 = arr6.T     #Matriz transposta
arr7

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [46]:
arr8 = np.concatenate((arr5, arr7))
arr8

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [49]:
np.split(arr7, 2)             #separar os arrays

[array([[0, 4],
        [1, 5]]),
 array([[2, 6],
        [3, 7]])]